# Copyright 2020 Cray Inc. All Rights Reserved.
#
---
- hosts: spines_mtl
  gather_facts: false

  tasks:

    - name: Check if BGP is enabled
      onyx_command:
        commands:
          - show protocols | include bgp
      vars:
        ansible_command_timeout: 60
      register: bgp_enabled
      ignore_errors: true
      changed_when: false

    - name: Check if BGP is configured
      onyx_command:
        commands:
          - enable
          - show ip bgp summary
          - disable
      vars:
        ansible_command_timeout: 60
      register: bgp_check
      changed_when: false
      when:
        - bgp_enabled.stdout is defined
        - "'enabled' in bgp_enabled.stdout[0]"

    - name: Check BGP status
      block:

      - name: Check the BGP status on spine switches
        onyx_command:
          commands:
            - enable
            - show ip bgp summary
        vars:
          ansible_command_timeout: 60
        register: result

      - debug:
          msg: "{{ result.stdout[1] }}"

      when:
        - bgp_enabled.stdout is defined
        - "'enabled' in bgp_enabled.stdout[0]"
        - bgp_check.stdout is defined
        - "'router identifier' in bgp_check.stdout[1]"
